env:
  browser: true
  es2021: true
  node: true
plugins:
  - jest
  - fp
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended' 
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  fp/no-mutation: "error"
  fp/no-let: "error"
